### ISSUE TITLE
Support json with nested structure

### ISSUE THREAD

**Issue by Metilar** [xiCO2k/laravel-vue-i18n#53]
Vue i18n supports json with a nested structure.

JSON:
```
{
  message: {
    hello: 'Hello world'
  }
}
```
Template:
```
<p>{{ $t('message.hello') }}</p>
```

I tried that, but the translation returns the keys.

**Comment by xiCO2k** [comment]
Hey @Metilar can you check if that works, on the PHP side with the `{{ _('message.hello') }}`?

Thanks for the help.

**Comment by xiCO2k** [comment]
Hey @Metilar just tested on just the Laravel stack and its not supported.

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/823088/184018869-ac8c61c0-b6ff-4216-b6cf-e31a8238c61f.png">

Since this package follows the i18n rules from Laravel I will not add that for now, if you want to PR that to the Laravel core, then I will be happy to include here.

Thanks.

**Comment by onlime** [comment]
@taylorotwell has rejected https://github.com/laravel/framework/pull/42226 in May 2022, just for reference. I would still love to see this happen in both Laravel and laravel-vue-i18n, but find it smart you follow strict i18n rules from Laravel in this package.
